### ISSUE TITLE
Handle environment variables

### ISSUE THREAD

**Issue by emartinez-dev** [Juan-aga/Minishell#13]
- [ ] Handle environment variables

**Comment by Juan-aga** [comment]
Created the function *ft_getenv(char *str, t_ms *ms). It returns a pointer to the value of the variable in ms->env.
@emartinez-dev now it's pending the lexer.

**Comment by Juan-aga** [comment]
MOD: function "t_envlst *ft_getenv(char *str, t_ms *ms). It now return a pointer to the node of envlst of ms->exp.
if it exist we the value if in value variable of the node.
else returns NULL.

**Comment by emartinez-dev** [comment]
Done, I have created the function `void	expand_tokens(t_lexer *lexer, t_ms *ms)` that checks if there is any env variable in the token and replaces it
