### ISSUE TITLE
Handle $?

### ISSUE THREAD

**Issue by emartinez-dev** [Juan-aga/Minishell#14]
- [x] It should expand to the exit status of the most recently executed foreground pipeline

**Comment by Juan-aga** [comment]
the last exit status is in the variable ms->exit_status.

**Comment by emartinez-dev** [comment]
I am trying to reproduce it and the segfault happens like 70% of the time, but I tried to debug it with lldb and it works 100% of the time while debugging. I have been reading on [stackoverflow](https://stackoverflow.com/questions/4628521/segfault-only-when-not-using-debugger) and it could be that we have a data race reading the variable exit_status
