### ISSUE TITLE
Wildcards * for the current working directory

### ISSUE THREAD

**Issue by emartinez-dev** [Juan-aga/Minishell#24]

**Comment by Juan-aga** [comment]
@emartinez-dev function "char **ft_wildcard(char **ls)" it's created. 
if it found something returns it, else returns ls.
Provisionally there is a builtin that print the result to try it.
You only have to put for ex "wildcard *.c" and print on the screen what it found.

**Comment by emartinez-dev** [comment]
Implemented into the lexer function!
