### ISSUE TITLE
Child process exit status

### ISSUE THREAD

**Issue by emartinez-dev** [Juan-aga/Minishell#26]
## Description
When a child process returns an error code, the output is not the same as in bash

## How to reproduce
Remove a non existing file with rm and echo the last command exit code

## Result

```  
minishell  Minishell $> rm 123
rm: cannot remove '123': No such file or directory
minishell  Minishell $> echo $?
127
```

## Expected result
```
emartinez@Enrique-HP:~$ rm 123
rm: cannot remove '123': No such file or directory
emartinez@Enrique-HP:~$ echo $?
1
```

**Comment by Juan-aga** [comment]
Now if fails and it's only one command, exit status is 1
